apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  #configuration rules
  annotations:
    #dice a kubernets que utilize la clase de ingres de nginx
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/use-regex: "true"
    #quita el /api de cada request y lo reemplaza por /
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    # redirecciona cada ruta que comienza por el pad a un cluserIp y los pods
    - http:
        paths:
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: client-cluster-ip-service
                port:
                  number: 3000
          - path: /api/?(.*)
            pathType: Prefix
            backend:
              service:
                name: server-cluster-ip-service
                port:
                  number: 5000
